### ISSUE TITLE
extra \n char

### ISSUE THREAD

**Issue by stuta** [jsolman/luajit-mime-base64#1]
When I encode this I get extra \13\n chars in the middle of the result, otherwise it is ok. Is this a bug?

```lua
escape.encode("a1f34f12e9d47345599432f300748f714f97f8a4:5fb9eef8349924576e29aa69b3bd060e9d926deb") 
==
"YTFmMzRmMTJlOWQ0NzM0NTU5OTQzMmYzMDA3NDhmNzE0Zjk3ZjhhNDo1ZmI5ZWVmODM0OTkyNDU3\13\nNmUyOWFhNjliM2JkMDYwZTlkOTI2ZGVi"
```

**Comment by jsolman** [comment]
Not exactly a bug; mime limited the length of lines to 76 characters; see
the note in this RFC
https://www.ietf.org/rfc/rfc4648.txt

I’ll add a flag parameter to the method to not insert the line feeds if you
like. The Turbo web server project includes this code with an adjustment to
not emit the line feeds.

**Comment by jsolman** [comment]
I added the option to exclude the line feed and pushed the change. Enjoy.
